name: Atualizar Tabela README

on:
  workflow_run:
    workflows: ["Rodando Valuation Acoes"]
    types:
      - completed
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out o repositório
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          make install

      - name: Rodar script para atualizar o README
        run: python -m codigos_rodando.rodando_valuations # Supondo que o script seja "atualizar_readme.py"
      
      - name: Configure Git
        run: |
          git config --global user.email "sehnemjeferson@gmail.com"
          git config --global user.name "Jeferson Sehnem"

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.VALUATION_EMPRESAS }}
        run: |
          git add .
          if git diff-index --quiet HEAD; then
              echo "No changes to commit"
          exit 0
          fi
          git commit -m "Coletando dre em: $(date +'%Y-%m-%d')"
          git push https://Jeferson100:${{ secrets.VALUATION_EMPRESAS }}@github.com/Jeferson100/Valuation-Empresas-Brasileiras.git HEAD:main
